### ISSUE TITLE
The dependency references in the project cannot be found

### ISSUE THREAD

**Issue by olovholm** [documaster/ws-client-n5-java-samples#2]
We got an URL a to this repository to have a look at the examples in the code. When I try to download the dependencies stated in the [POM](https://github.com/documaster/ws-client-n5-java-samples/blob/master/pom.xml), Gradle can find neither of them. 

On the [MVNRepository](https://mvnrepository.com/artifact/com.documaster) site I can find similar dependencies, but with other name/artifact-ids. Does "documaster-ws-client-n5" correspond to "noark-ws-client" in this project?

**Comment by dkumanov** [comment]
Hello Ola,

The 2 Documaster client dependencies in the sample project POM are outdated indeed. In order to compile the sample you will need [the new noark5 ws client](https://mvnrepository.com/artifact/com.documaster.rms/documaster-ws-client-n5/1.5.1) and [the new idp client](https://mvnrepository.com/artifact/com.documaster.idp/documaster-ws-client-idp/1.0.0) definitions.

Note that the `businessSpecificMetadataSample` relies on some deprecated code, so you will need to delete that part for now.

We plan on updating the code base in the near future.

Let me know if that helps with your issue.

**Comment by olovholm** [comment]
Thank you for the quick reply and links to the new repositories! I'm able to download and integrate with those. Cheers!
